### ISSUE TITLE
[Tcl>=9.0] Python error when trying to show AudioBuffer

### ISSUE THREAD

**Issue by alibarker** [maxmarsc/dave#9] opened 2024-11-14 14:34 UTC
When running dave on MacOS 14.5 using CLion I get the following error when trying to show a juce::AudioBuffer:
```
INFO: Added outputBuffer : 1
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/alistair.barker/.dave/venv/lib/python3.13/site-packages/dave/client/__init__.py", line 1, in <module>
    from .gui import DaveGUI
  File "/Users/alistair.barker/.dave/venv/lib/python3.13/site-packages/dave/client/gui.py", line 15, in <module>
    from .audio_views_tab import AudioViewsTab
  File "/Users/alistair.barker/.dave/venv/lib/python3.13/site-packages/dave/client/audio_views_tab.py", line 11, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
  File "/Users/alistair.barker/.dave/venv/lib/python3.13/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/Users/alistair.barker/.dave/venv/lib/python3.13/site-packages/matplotlib/backends/_backend_tk.py", line 25, in <module>
    from . import _tkagg
ImportError: Failed to load Tcl_SetVar
```

I wonder if it is related to this matplotlib issue: https://github.com/matplotlib/matplotlib/issues/29126

**Comment by maxmarsc** [comment] 2024-11-15 09:28
Hi ! Thanks for giving it a go !

Indeed it looks related. I've tested with a python3.13 installation but with tcl 8.6 and no issue rises.

I checked the Homebrew formula, and starting from python-tk>=3.12 they rely on the [tcl-tk](https://formulae.brew.sh/formula/tcl-tk) 9.0.0 package.

One temporary workaround would be to force MacOS users to use either python3.10 or python3.11 in the meantime, waiting for matplotlib to fix their issue.


Could you try the following code to test the 3.11 behaviour ?
```bash
brew install python-tk@3.11
python3.11 -c "from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg"
```


If this works I'll update the install script to check more precisely the python version when MacOS is detected

**Comment by chrhaase** [comment] 2024-11-15 16:50
Thanks! Will try this out in the weekend.

**Comment by chrhaase** [comment] 2024-11-18 09:55
Ok, this works!!
One thing, though: It seems that `dave uninstall` doesn't remove `.dave`, so when I reinstalled I got:
```
chrhaase@Chrilles-Mac-Mini ~ % bash -c "$(curl -fsSL https://raw.githubusercontent.com/maxmarsc/dave/refs/heads/main/dave/assets/dave_install.sh)"
Hello ! This is the installation script for dave. First thanks a lot for trying it out
...
Type Enter to continue
MacOS detected
Selection python3.11 for dave installation
With Tcl 8.6

/Users/chrhaase/.dave folder already exists. Aborting
```
Removing `.dave` manually and then uninstalling and reinstalling resolved it!

Another note: The issue seems to be fixed in matplotlib already, but I guess we have to wait for a tagged release :)

**Comment by maxmarsc** [comment] 2024-11-18 10:06
Great :partying_face: 

Oh you're right, that's another bug ^^" I'll look into it, probably create an issue for it

I need to know, did you created a subfolder for custom containers support in `~/.dave` before uninstalling ?
If so when uninstalling did you kept that subfolder ?

**Comment by chrhaase** [comment] 2024-11-18 10:11
Nope, didn't make any subfolder!

**Comment by maxmarsc** [comment] 2024-11-18 10:27
Hmm, that's weird. I'm not able to reproduce this. I fixed another related bug just now though.

If you're able to reproduce the bug would you please be kind enough to create another issue for it @chrhaase ?

I'll close this one and allow Tcl 9.0 when the next matplotlib version is released

**Closed by maxmarsc** 2024-11-18 10:27 UTC
Labels: bug
